<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="D-INE-BQ57BS2" failures="1" tests="1" name="Default test" time="12.986" errors="0" timestamp="2023-11-29T12:58:20 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.524">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at stepDefinition.StepDefinitionOfWebsite.user_sees_the_added_customer_details(StepDefinitionOfWebsite.java:116)
at âœ½.user sees the added customer details(file:///C:/Users/vmalarvannan/Downloads/Venture_Vultures-OrangeHRM/src/test/resources/Feature/Time.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
